### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'addr'

### ISSUE THREAD

**Issue by ghost** [axt/angr-utils#11]
Hay,

I've just tried to give the  examples/plot_cfg example a go but keep receiving the "AttributeError: 'NoneType' object has no attribute 'addr'" error. I've tried a couple of PE32 executables but get the same error with all of them, I'm guessing it's an issue with the fact I'm targeting PE files? 

Thanks

**Comment by axt** [comment]
Hi! Sorry for my late answer. PE files are supported. Its hard to say anything without an explicit backtrace, or binary, but my guess is that your binary doesn't contain the symbol you are looking for, so the variable `main` will be null at ([*]), and it throws the error when the code tries to read its `addr` property in the next line.

```
if __name__ == "__main__":
    proj = angr.Project("../samples/ais3_crackme", load_options={'auto_load_libs':False})
[*]    main = proj.loader.main_bin.get_symbol("main")
    analyze(proj, main.addr, "ais3")
```  

If you think its not the case, you can give me your script and a backtrace, or the script and the binary, and I can have a look on the error.
