### ISSUE TITLE
Problem with fauxware file

### ISSUE THREAD

**Issue by mtaiuit** [axt/angr-utils#12]
I creat cfg with crackme0x00a file -> success. But error with fauxware file. This is error. Please, help me.
![screenshot from 2017-06-09 00-23-39](https://user-images.githubusercontent.com/12328883/26942412-22551d34-4cac-11e7-9030-3e72a7e52191.png)

**Comment by axt** [comment]
I've tried a quick check with `CFGFast` for all functions, and `CFGAccurate` for the `authenticate` function, and its working for me. Can you provide me the script you are using to generate the cfg and attach the binary you are using?

**Comment by frapik99** [comment]
Hi all, I know that this "is not" my issue but I had the same problem trying to create the png for ```png_write_IEND```. I used the following script:

```
In [15]: name = "png_write_IEND"
In [16]: proj = angr.Project("./libpng16.so.16", load_options={'main_opts': {'custom_base_addr':0x0},
    ...:  'auto_load_libs':False})
    ...: sym = proj.loader.main_bin.get_symbol(name)
    ...: addr = sym.addr
    ...: start_state = proj.factory.blank_state(addr=addr)
    ...: start_state.stack_push(0x0)
    ...: cfg = proj.analyses.CFGAccurate(fail_fast=True, starts=[addr], initial_state=start_state, co
    ...: ntext_sensitivity_level=2, keep_state=True, call_depth=100, normalize=True)
    ...: plot_cfg(cfg, name , asminst=True, vexinst=False, debug_info=False, remove_imports=True, rem
    ...: ove_path_terminator=True)
```

```
    132 
    133     def remove_node(self, node):
--> 134         self.nodes.remove(node)
    135         self.edges = filter(lambda edge: edge.src != node and edge.dst != node, self.edges)
    136 
KeyError: <bingraphvis.base.Node object at 0x7f7219786c10>
```

HTH

**Comment by axt** [comment]
Hi! Sorry for my late answer!  

Pushed a fix for this error: https://github.com/axt/bingraphvis/commit/dda79f8ce358b573b68f92a65d6ff8885139e27c should fix it, please refresh and try.
