### ISSUE TITLE
Installation problem with virtualenv

### ISSUE THREAD

**Issue by albus12138** [axt/angr-utils#14]
Hello, @axt 
I installed angr in virtualenv. And I want to install angr-utils in virtualenv too. But when I execute "python setup.py install" in virtualenv :
`(angr_env) raphael@ubuntu:~/Desktop/angr-utils-0.3.0$ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/angr_utils-0.3.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/angr_utils-0.3.0.egg-info`
Ubuntu 17.04, Python 2.7.13

How can I install this in virtualenv?

**Comment by axt** [comment]
Hi! Sorry for my late answer. Unfortunatelly I'm not good/familiar with python packaging. 

It seems to me that it is just a warning. Does 
```
import angrutils
```
throw an error? Or maybe did the install succeed?

I myself use this to install the packages:
```
pip install -e ./bingraphvis
pip install -e ./angrutils
```
