### ISSUE TITLE
plot_cfg not working 

### ISSUE THREAD

**Issue by R3x** [axt/angr-utils#15]
I am not able to plot graphs. Even the example files that you have given are not working.

`/home/siddhu/.virtualenvs/angr/lib/python2.7/site-packages/bingraphvis/angr/factory.pyc in default_cfg_pipeline(self, cfg, asminst, vexinst, remove_path_terminator, color_edges, comments)
     19             vis.add_content(AngrAsm(project))
     20             if comments:
---> 21                 if cfg.sort == 'fast':
     22                     if project.arch.name in ('X86', 'AMD64'):
     23                         vis.add_content_annotator(AngrX86CommentsAsm(project))

AttributeError: 'CFGAccurate' object has no attribute 'sort'
`

**Comment by axt** [comment]
Hi! Thanks for the report. Most probably CFGBase was changed in the latest angr relase. 

I will not have time to look into this deeper during this week.  

As a workaround, you could try to call it with 'comments=False' parameter, or modify https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/factory.py to solve the error, by keeping only these lines 
```
if comments:
    vis.add_content_annotator(AngrCommentsAsm(project))
```
I can't promise that if you try these workarounds, they will help. The latest angr release was a big ones, maybe there are some other broken dependencies. I will fix it on next week.

**Comment by R3x** [comment]
I did try it with 'comments = False' but there are other errors.

**Comment by axt** [comment]
Which version are you using? I've updated my env to the latest angr, and I don't get any errors. 

My guess is that you are using an old version of angr, which is probably not supported by this tool.
