### ISSUE TITLE
how to speed up cfg_path

### ISSUE THREAD

**Issue by xuehongfa** [axt/angr-utils#16]
I am using the cfg_path to collect all the possible path in the CFG for each function. However, it takes forever. Is there any way to speed up? Or another way to obtain all the paths in CFG?

**Comment by axt** [comment]
The `cfg_path` example is just to demonstrate, how can you highlight a path on the CFG. 

In the example, I do a symbolic exploration of the underlying program, to get some paths, but this is impossible to do with larger CFGs. Basically if you have a loop in the CFG, then you can easily have an infinite number of different paths (depending on how many time the loop was executed), but even if you iterate all the loops only once, every branch instruction in the CFG doubles the number of possible paths, so it goes exponentially with the number of branch instructions.

The answer to your question is heavily depending on why do you need all the paths. 

For example, you can generate all the possible paths just based on the graph without simulating anything, but then you will have some paths, that will never happen in real when executing the program.
