### ISSUE TITLE
No module named "expr"

### ISSUE THREAD

**Issue by kamakazikamikaze** [axt/angr-utils#20]
When executing `from angrutils import *`, the following error occurs:
```
c:\users\sandbox\.virtualenvs\angr-aoudwqk0\lib\site-packages\angrutils\pp.py in <module>
      4 import claripy
      5 import simuvex
----> 6 from expr import *
      7
      8 def pp(obj, **kwargs):

ModuleNotFoundError: No module named 'expr'
```
Looking at the other files in the package, it would seem that the line should be changed to `from .expr import *` as it is a local module

**Comment by yampelo** [comment]
@axt  needs to push the latest version to pypi, it looks like its fixed in the code:

https://github.com/axt/angr-utils/blob/master/angrutils/pp.py#L5

**Comment by axt** [comment]
Sorry, I was a bit "off-the-grid". 
Its already midnight here, but will create pypi versions tomorrow! 
Sorry for the delay!

**Comment by axt** [comment]
Pushed the new version to pypi! I'm really sorry, that it took me so long.
