### ISSUE TITLE
Is there a way to walk a dissasembly graph?

### ISSUE THREAD

**Issue by DainTorson** [axt/angr-utils#29]
Hello!

I intent to automaticaly analyze CFG graphs of binaries in order to find some properties of packers. The graph generated by simply running CFGFast() is not very easy to analyse as it's only a graph of addresess (as far as I cat tell). Is the a way to get this nice CFG representation in basic blocks, which is generated by plot_cfg(), and walk through it?

Thanks in advance!

**Comment by axt** [comment]
Hi, sorry for my late answer!

The CFG generated by angr contains CFGNodes, which only contain the metadata for the basic blocks, but not the actual instructions. If you need the actual instructions, you need to ask angr to lift them for you. 

Check the docs here:
https://docs.angr.io/core-concepts/toplevel#blocks

Here is how ang-utils does it ():
https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/content.py#L259

And here is the code, what calculates the parameters for the previous function, from a CFG node input:
https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/content.py#L216-L220

The same is true if you want to get back VEX instructions:
https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/content.py#L376
https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/content.py#L333-L338

**Comment by DainTorson** [comment]
Thanks!
