### ISSUE TITLE
Regarding CFG construction

### ISSUE THREAD

**Issue by monowaranjum** [axt/angr-utils#35]
Hi, Here is the source code of the program I am trying to construct a call graph of: 

```
#include <stdio.h>

void A(){}
void B(){}
void C(){A();}
void D(){B();}
void E(int x){
	if ( x>0){ D(); }
	else{ C(); }
}

int main(int argc, char *argv[]){
	FILE *fp;
	fp  = fopen("input.txt","r");
	return 0;
	E(2);
}
```
Here is the generated CFGFast by angr which is drawn by angr-utils. Shouldn't the rightmost strongly connected component (Function E) should be somehow connected to the ending block of main? Why is that component completely disconnected from the main function graph?   Thanks in advance.
![a2_dyn_cfg](https://user-images.githubusercontent.com/19803082/209462093-cbef25fa-17dc-4c10-9e06-09c328f9d239.png)

**Comment by axt** [comment]
Hey! Since the main always returns before it would call E, the compiler doesn't put the call into the binary code, since it never can happen.
