### ISSUE TITLE
Need a new Sample?

### ISSUE THREAD

**Issue by windhl** [axt/angr-utils#7]
hi, AXT, I run your sample code with newest angr and got several errors, and I fix it like this:

import angr
from angrutils import *
proj = angr.Project("./test", load_options={'auto_load_libs':False})
main = proj.loader.main_bin.get_symbol("main")
#start_state = proj.factory.blank_state(addr=main.addr)
start_state = proj.factory.entry_state()
#cfg = proj.analyses.CFGFast(fail_fast=True, starts=[main.addr], initial_state=start_state)
cfg = proj.analyses.CFG()
plot_cfg(cfg, "ais3_cfg", asminst=True, remove_imports=True, remove_path_terminator=True)

anyway, your work is great!

**Comment by axt** [comment]
Hi! I don't get what do you mean. 

I've checked all the examples, and they are functional without errors in my environment.

Do you run into any specific problem?

**Comment by windhl** [comment]
Sorry, maybe I use the different version of angr with you. I got the error like these:
======================================================
Traceback (most recent call last):
  File "cfg.py", line 5, in <module>
    start_state = proj.factory.blank_state(addr=main.addr)
AttributeError: 'NoneType' object has no attribute 'addr'
======================================================
Traceback (most recent call last):
  File "cfg.py", line 7, in <module>
    cfg = proj.analyses.CFG(fail_fast=True, starts=[main.addr], initial_state=start_state)
AttributeError: 'NoneType' object has no attribute 'addr'
=======================================================

**Comment by windhl** [comment]
Sorry, maybe I use the different version of angr with you. I got the error like these:

Traceback (most recent call last):
File "cfg.py", line 5, in 
start_state = proj.factory.blank_state(addr=main.addr)
AttributeError: 'NoneType' object has no attribute 'addr'

Traceback (most recent call last):
File "cfg.py", line 7, in 
cfg = proj.analyses.CFG(fail_fast=True, starts=[main.addr], initial_state=start_state)
AttributeError: 'NoneType' object has no attribute 'addr'

**Comment by axt** [comment]
I tested it with the latest version of angr. 

The error means, that your `test` binary doesn't have a symbol named `main`. 

Also please note, that `CFG` is a wrapper for `CFGFast`, it doesn't have parameters like `starts` and `initial_state` (they are parameters for `CFGAccurate`), although it will not fail if you specify those, but it will print out some warnings.
